WIP LGA-1822 Confirmation-page-with-call-back-reference-number
ministryofjustice/cla-end-to-end-tests pull request #18
Opened 2022-03-09 16:40 UTC by jogilder

Added in steps for callback scenario. 
This is WIP as several TODOs once LGA-1821 has been merged such as steps being removed. This won't run as is, it is missing some of the files from the LGA-1821 branch.

2022-03-15 11:54 UTC, said-moj requested changes

2022-03-16 09:30 UTC, jogilder commented on behave/features/steps/cla_eligible_callback.py
> +def step_means_test_page(context):
this has now been removed as the previous commit has been merged.

2022-03-16 09:32 UTC, jogilder commented on behave/features/steps/cla_eligible_confirmation.py
> +    # pdb.set_trace()
this is the only place it exists.

2022-03-16 09:32 UTC, jogilder commented on behave/features/cla_eligible_callback.feature
> +  And The callback should have been created
Ok, will do.

2022-03-16 12:20 UTC, said-moj approved these changes
👍 LGTM

2022-03-16 12:44 UTC, merged