Feature/lga 2411 format a11y json
ministryofjustice/cla-end-to-end-tests pull request #96
Opened 2023-04-13 12:53 UTC by psweeting1

## What does this pull request do?

Formatting axe.result dictionary file to only report points of interest in the a11y.json file. Report now only includes violations found in accessbility testing. This has been changed into a json format as well which has better readability.

After all of the tests have been run, the filter_accessibility_report() function creates a second  a11y_filtered.json which filters out and duplicated accessibility violations the report has found. 

## Any other changes that would benefit highlighting?

- Updated README.md file to include how to use accessibility tests in cla_end_to_end
- Updated Git Ignore to stop trying to include downloaded CSV files from tests into the repo
- Removed redundant class variable `accessibility_check = False`  

## Checklist

- [LGA-2411](https://dsdmoj.atlassian.net/browse/LGA-2411)

[LGA-2411]: https://dsdmoj.atlassian.net/browse/LGA-2411?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-04-14 10:33 UTC, Pheonnexx submitted a review, later dismissed
LGTM

2023-04-20 14:25 UTC, sarahyjja requested changes

2023-04-20 14:25 UTC, sarahyjja commented on behave/features/steps/common_steps.py
> +    results_to_copy = []
Could we rename `results_to_copy` with something more descriptive? _E.g.: `filtered_issues` (or else)_

2023-04-20 14:25 UTC, sarahyjja commented on behave/features/steps/common_steps.py
> +    for error in data:
Could we rename `error` with something more descriptive? _E.g.: `step_error` (or else)_

2023-04-21 08:18 UTC, sarahyjja approved these changes
LGTM

2023-04-21 08:57 UTC, sarahyjja approved these changes

2023-04-21 11:00 UTC, Pheonnexx approved these changes
LGTM 🚀

2023-04-21 13:38 UTC, merged